extends:
  - airbnb
  - plugin:flowtype/recommended
plugins:
  - react
  - jsx-a11y
  - import
  - flowtype
rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  react/jsx-filename-extension:
    - 1
    - extensions:
      - .js
      - .jsx
